# Generated by Django 4.1.7 on 2023-03-15 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('idEntrenador', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEntrenador', models.CharField(max_length=200)),
                ('apodoEntrenador', models.CharField(max_length=200)),
                ('fechaNacimientoEntrenador', models.DecimalField(decimal_places=0, max_digits=4)),
                ('nacionalidadEntrenador', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idEquipo', models.AutoField(primary_key=True, serialize=False)),
                ('codigoEquipo', models.CharField(max_length=200)),
                ('nombreEquipo', models.CharField(max_length=200)),
                ('anioFundacionEquipo', models.DecimalField(decimal_places=0, max_digits=4)),
                ('escudoEquipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('idJugador', models.AutoField(primary_key=True, serialize=False)),
                ('nombreJugador', models.CharField(max_length=200)),
                ('apodoJugador', models.CharField(max_length=200)),
                ('nacionalidadJugador', models.CharField(max_length=200)),
                ('fechaNacimientoJugador', models.DateTimeField(verbose_name='fecha de nacimiento')),
                ('alturaJugador', models.DecimalField(decimal_places=3, max_digits=5)),
                ('numeroFavorito', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('idPosicion', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePosicion', models.CharField(max_length=200)),
                ('estadoPosicion', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JugadorEquipoTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicioContrato', models.DateField()),
                ('fechaFinContrato', models.DateField()),
                ('dorsalJugador', models.DecimalField(decimal_places=0, max_digits=2)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendProyecto.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendProyecto.jugador')),
            ],
            options={
                'unique_together': {('jugador', 'equipo')},
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='equipos',
            field=models.ManyToManyField(through='backendProyecto.JugadorEquipoTiempo', to='backendProyecto.equipo'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendProyecto.posicion'),
        ),
        migrations.CreateModel(
            name='EntrenadorEquipoTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicioContrato', models.DateField()),
                ('fechaFinContrato', models.DateField()),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendProyecto.entrenador')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendProyecto.equipo')),
            ],
            options={
                'unique_together': {('entrenador', 'equipo')},
            },
        ),
        migrations.AddField(
            model_name='entrenador',
            name='equipos',
            field=models.ManyToManyField(through='backendProyecto.EntrenadorEquipoTiempo', to='backendProyecto.equipo'),
        ),
    ]
