# Generated by Django 4.1.7 on 2023-03-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendProyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='equipos',
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(through='backendProyecto.JugadorEquipoTiempo', to='backendProyecto.jugador'),
        ),
    ]
