# Generated by Django 4.1.7 on 2023-03-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendProyecto', '0004_alter_entrenador_fechanacimientoentrenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='fechaNacimientoEntrenador',
            field=models.DateTimeField(verbose_name='fecha de nacimiento'),
        ),
    ]
