# Generated by Django 4.1.7 on 2023-03-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendProyecto', '0005_alter_entrenador_fechanacimientoentrenador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='jugadores',
        ),
        migrations.AddField(
            model_name='jugador',
            name='Equipo',
            field=models.ManyToManyField(through='backendProyecto.JugadorEquipoTiempo', to='backendProyecto.equipo'),
        ),
    ]
