# Generated by Django 4.1.7 on 2023-03-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendProyecto', '0006_remove_equipo_jugadores_jugador_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenador',
            name='equipos',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='Equipo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='entrenador',
            field=models.ManyToManyField(through='backendProyecto.EntrenadorEquipoTiempo', to='backendProyecto.entrenador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(through='backendProyecto.JugadorEquipoTiempo', to='backendProyecto.jugador'),
        ),
    ]
