# Generated by Django 4.1.7 on 2023-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendProyecto', '0007_remove_entrenador_equipos_remove_jugador_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='escudoEquipo',
            field=models.ImageField(upload_to=''),
        ),
    ]
